Added contributing guidelines in CONTRIBUTING.md
orca-services/cakephp-swagger-ui pull request #3
Opened 2020-10-23 06:36 UTC by Richard-Strittmatter

Since our other open source projects have a contributing guide, I thought this one should have one aswell.

2020-10-26 16:17 UTC, ravage84 requested changes

2020-10-26 16:17 UTC, ravage84 commented on CONTRIBUTING.md
> +* The code must follow the [CakePHP coding standard](http://book.cakephp.org/2.0/en/contributing/cakephp-coding-conventions.html).
This schould point to the CakePHP 3.x documentation page

2020-10-26 16:17 UTC, ravage84 commented on CONTRIBUTING.md
> +    vendor/bin/phpcs -p --extensions=php --standard=CakePHP
We should promote the ``composer cs-check`` command here.

2020-10-27 10:31 UTC, ravage84 approved these changes
@TerryKern please also review this PR

2020-10-27 12:41 UTC, TerryKern approved these changes
Looks good to me.

2020-10-27 12:46 UTC, merged